# Generated by Django 6.0 on 2025-12-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_highlight'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('link_text', models.CharField(blank=True, default='Register Now', max_length=50)),
                ('link_url', models.CharField(blank=True, default='/events', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'News',
                'ordering': ['-created_at'],
            },
        ),
    ]
