# Generated by Django 6.0 on 2025-12-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('DOCUMENT', 'Document'), ('VIDEO', 'Video / Tutorial'), ('LINK', 'External Link'), ('CODE', 'Code / Repository')], default='LINK', max_length=20),
        ),
    ]
