# Generated by Django 6.0 on 2025-12-16 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_resource_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
