# Generated by Django 6.0 on 2025-12-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_link',
            field=models.URLField(blank=True, help_text='Link to external registration (Google Forms, Luma, Meetup, etc.)', null=True),
        ),
    ]
